name: Build and Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '9.x'

      - name: Restore dependencies
        run: dotnet restore StringLibrary/StringLibrary/StringLibrary.csproj 

      - name: Build
        run: dotnet build StringLibrary/StringLibrary/StringLibrary.csproj --configuration Release  

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '9.x'

      - name: Restore dependencies
        run: dotnet restore StringLibrary/StringLibrary/StringLibraryTest/StringLibraryTest.csproj 
      - name: Run tests
        run: dotnet test StringLibrary/StringLibrary/StringLibraryTest/StringLibraryTest.csproj --configuration Release 
